### ISSUE TITLE
Permission clarification

### ISSUE THREAD

**Issue by deardooley** [DICE-UNC/jargon#138]
Can you clarify the jargon permission model vs the irods model? I'm unclear how Jargon reading vs writing permissions. I see this snippet in `DataObjectAOImp#setAccessPermission`

``` java
        if (filePermission == FilePermissionEnum.OWN) {
            setAccessPermissionOwn(zone, absolutePath, userName);
        } else if (filePermission == FilePermissionEnum.READ) {
            setAccessPermissionRead(zone, absolutePath, userName);
        } else if (filePermission == FilePermissionEnum.WRITE) {
            setAccessPermissionWrite(zone, absolutePath, userName);
        } else if (filePermission == FilePermissionEnum.NONE) {
            removeAccessPermissionsForUser(zone, absolutePath, userName);
        } else {
            throw new JargonException(
                    "Cannot update permission, currently only READ, WRITE, and OWN, and NONE are supported");
        }
```

This has been an ongoing question for me, so I thought I'd pose it formally here:
1. It looks like I can't set anything other than one of three discrete permissions, `FilePermissionEnum#OWN`, or `FilePermissionEnum#NONE`. Is there an interface for permission arithmatic I should consult? 
2. What is the order of precedence when setting the permissions?  `FilePermissionEnum#getPermissionNumericValue` does not follow unix ordering, so what is the expected behavior when adding one permission to an existing permission? 
3. From my tests, it looks like setting `FilePermissionEnum#WRITE` permission on a file you own results in a `FilePermissionEnum#MODIFY_METADATA` permission (which is returned as `modify object` by the iCommands, and `modify` by `FilePermissionEnum#MODIFY_METADATA#name` and `FilePermissionEnum#MODIFY_METADATA#toString`). What does it mean to remove a permission? 
4. `FilePermissionEnum#EXECUTE` has a smaller  `#permissionNumericValue` value than `FilePermissionEnum#READ`. so does removing `FilePermissionEnum#READ` permission imply the user should have `FilePermissionEnum#EXECUTE` permission? 
5. Should we assume the user always has `READ` when they have `WRITE` permission?
6. What is the intended behavior when the owner of a data object or collection removes their permission on an object? Should they be able to add it back in, or should they be treated as a normal user from then on?

**Comment by michael-conway** [comment]
I'm sending this to Jason and Terrell to see what comments they may have......

**Comment by trel** [comment]
The iRODS permission model is linear.  It has 18 levels of granularity by design, but in practice, only four are used (OWN, WRITE, READ, NULL).

You can see it defined and commented in the code:
  https://github.com/irods/irods/blob/master/iRODS/server/icat/include/icatDefines.h#L32
and
  https://github.com/irods/irods/blob/master/plugins/database/src/icatSysInserts.sql#L59


To answer your questions more directly:

1) Correct, there are three plus null.  No arithmetic is required, just a comparison.

2) As I understand it, setting the permission to the 'greater' value is all that is necessary.

3) There is inconsistency with how the simplified concept of 'WRITE' is conveyed and how it is stored as one of the 18 levels.  Namely, WRITE is interpreted as 'modify object'.  Permission on an object itself is currently implemented as having the same permission on the object's metadata - there are not separate controls on the metadata at this time.

4) I'm going to leave this to @michael-conway, I'm not sure what Jargon is doing about the permission model directly.

5) Yes - it's linear, and therefore included.

6) This is part of issue irods/irods#1992.  There is an additional field in the iCAT database that holds original 'primary owner'.  This is not exposed in the API (via iCommands, or Jargon) and serves as a safeguard against someone removing their own access.  However, it causes confusion as the permission model is clouded by its existence.  To answer your question, the user will be able to add permission back to their own object (because they are the original primary owner).  Exposing/Updating that value is the topic of discussion within irods/irods#1992.  It is an open question at this time.  Please weigh in if you have a particular use case and/or concerns.

**Comment by trel** [comment]
Also see the discussion at https://github.com/irods/irods/issues/844

**Comment by deardooley** [comment]
Thank you @trel that clears things up. I will implement appropriately. 

I took the broader permission conversation to [irods/irods#844](irods/irods#844). I think it's entirely relevant to Jargon, but Jargon already has too much bloat implementing use cases that should be handled by the server. Permission discovery and management should be done on the server side. Permission policy should be done at the application layer. Jargon shouldn't be doing anything more than translation to/from enumerations and error messages. 

What's in there now, IMHO, is appropriate save for the loss of all unix permissions when interacting with IRODS. The same thing happens when writing to an object store, so it's not really that unusual, but given the ubiquitous use of linux by the IRODS community, the lack of permission preservation stands out as a missed opportunity to create a better developer experience.

**Comment by michael-conway** [comment]
Yep, in the past, Jargon had to overhead a lot of things that the server would not do, and we're now seeing a migration back to the server, especially as the new API starts feeding in.
