### ISSUE TITLE
How to get MD5sum/sha256 sum for files using Jargon?

### ISSUE THREAD

**Issue by markehammons** [DICE-UNC/jargon#239]
I don't see any option for it on IRODSFile.

**Comment by michael-conway** [comment]
Hi Mark,

The Checksumming is not part of the java.io.File contract, so it can be
called explicitly like this:

https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/pub/DataObjectAO.java#L1185-L1195

Note that when you put files via data transfer, it can also automatically
compute or compute+verify checksum automatically.

the Jargon properties can be set to do this by default.  I can give you a
gist for how to set jargon properties programatically and it will just
happen.

This can also be set per operation for those operations that take a
TransferControlBlock as a parameter.  That block allows you to set various
parameters that otherwise are picked up by Jargon properties.

Happy to provide an example based on your use case!

MC

**Comment by markehammons** [comment]
I'm trying to provide an HTTP api for my irods server, so I need to double-check the data sent to the rest api. Is there a way to use an authentication token for irods instead of a username/pass? It'd be nice if I could give users a limited use authentication token for jargon accesses.

**Comment by michael-conway** [comment]
Interestingly, we had a rest API we were building in DFC, which is
released. At the same time I work with the Consortium at RENCI.

We are currently in a phaseII of REST development, where we'll see multiple
REST api services in a microservices architecture.  The 'base rest' may be
very similar to what you describe.  We are currently in a test slice model
here

https://github.com/DFC-Incubator/base-service/tree/spring4

(Note the spring4 branch).

This moved from RestEASY to Spring4 REST services so that we could more
easily use Spring Security4, which would indeed allow us to incorporate
Oath tokens by configuration.  That was our thinking too. Since we already
work with CyVerse discovery environment in DFC, I was looking at using CAS
as our Oauth server, though Spring Security works with any Oath/Oath2
service.

This next rev of REST is a big departure. We are using Swaggar first API
development, adding live integration testing to the suite, and focusing on
Spring Boot and Docker for deployment.  That all has now been tested in
that branch.  I still have to add in the CORS stuff and we should have a
live infrastructure, everything else is now working.

The status there is we'll move to using Swagger editor to fill out the
specification of the API, generate the stubs, and fill it in using that
base-rest framework.

If you are at a starting point and have not made any code commitments yet,
I'd invite you to take a look at where that's going, and if you want to
just add to that effort, you are most welcome.

**Comment by markehammons** [comment]
Unfortunately, though I haven't made a commitment yet, it has to be developed pretty urgently and will be rather basic. I'm basically planning on piping http data into and IrodsOutputStream after doing authentication based on our own servers (unfortunately, we do not currently use the security features of irods :( ). If I have time after I implement this quick rest service I'll try to help out though :).

**Comment by michael-conway** [comment]
Sure, I'm sure you could bring back some lessons learned.  If you've not
invested up front time, consider the use of SpringSecurity for token
support.  To accomplish this, you can keep a proxy iRODS account in the mid
tier and use it to 'run as' the logged in user.  There is a proxy user in
the iRODS account for this purpose.  That's how DE works.  I can point you
to Tony at CyVerse where they use this technique in production.

But that's how I intend to support OAuth in the upcoming REST API.
