### ISSUE TITLE
getResource() is an empty string

### ISSUE THREAD

**Issue by jjkoehorst** [DICE-UNC/jargon#416]
I was trying to find out if a file was stored on disk or on tape but within java I only get an empty string when asking for the resource of an irodsfile object.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/4471699/205245904-9887e7ed-36a5-408a-9d30-6287848170ba.png">

while via the CLI I do get the resource

<img width="226" alt="image" src="https://user-images.githubusercontent.com/4471699/205246051-b1e5c745-2408-4bf5-8d7d-4e60be3643b6.png">

Do I need to use another file object type to enable the getResource function?

**Comment by jjkoehorst** [comment]
Not sure why resource is an empty string or maybe it means something else but the resource can be obtained via

dataObjectAO.getResourcesForDataObject...

**Comment by korydraughn** [comment]
The behavior described is intentional/expected.

See the following:
https://github.com/DICE-UNC/jargon/blob/6f8e49201d14c95b4acfe0fcee18f4a18ce937e8/jargon-core/src/main/java/org/irods/jargon/core/pub/io/IRODSFile.java#L192-L211

The requested info does not come from the server, but from the user/client.

There are a number of ways to retrieve this info:
- Use `DataObjectAO.getResourcesForDataObject()`
- Use `ResourceAO.listResourcesForIrodsFile()`
- Use GenQuery
