### ISSUE TITLE
4.3.4.0 release activities

### ISSUE THREAD

**Issue by trel** [DICE-UNC/jargon#449]
- bump version numbers
  - [x] https://github.com/DICE-UNC/jargon-pom
  - [x] https://github.com/DICE-UNC/jargon
  - [x] https://github.com/DICE-UNC/jargon-extensions-jwt
  - [x] https://github.com/DICE-UNC/jargon-extensions-if
  - [x] https://github.com/DICE-UNC/jargon-irods-ext
  - ~https://github.com/DICE-UNC/jargon-extensions~
- [x] update readme 
- [x] update changelog
- [x] publish release artifacts to maven repo

**Comment by korydraughn** [comment]
Do not close this issue until after iRODS 4.3.3 is released and Jargon is tested against it.

**Comment by korydraughn** [comment]
The jargon-extensions repo hasn't been changed in 7 years. Is it still in use by anyone?

Given we don't know whether all of these repos are in use, I'm thinking we start with the following repos:
- jargon-pom
- jargon
- jargon-irods-ext

If we need to release updates for the other repos, then we can do so following the release of the three listed above.

Thoughts?

**Comment by trel** [comment]
https://github.com/DICE-UNC/jargon-extensions-if
and
https://github.com/DICE-UNC/jargon-extensions-jwt

have more recent updates - within the last couple years.

**Comment by korydraughn** [comment]
Is there a way to see if they are in use?

**Comment by korydraughn** [comment]
NFSRODS depends on jargon. Metalnx depends on jargon and jargon-irods-ext.

I don't know of anyone using the other repos.

**Comment by trel** [comment]
perhaps check the listing at https://irods.org/clients/

**Comment by korydraughn** [comment]
I've confirmed all repos are required _(to an extent)_.
- metalnx depends on jargon-irods-ext
- jargon-irods-ext depends on jargon-extensions-if
- jargon-extensions-if depends on jargon-extensions-jwt

I couldn't figure out how to compile jargon-irods-ext without removing the jaxb2-maven-plugin configuration. The configuration for that project used a very old version of the jaxb2 plugin. I don't know what depends on that, but removing it allowed me to compile the project.

If we're going to take over this project, I think we need to consider dropping all repos except jargon-pom and jargon. The consortium maintains Metalnx and the plan for that project is to either rip out everything so that it only depends on jargon or replace the project entirely.

Let's discuss.

**Comment by korydraughn** [comment]
Forgot to mention - if Metalnx works without the jaxb2 dependency, then we're likely ok. However, we don't have a way to verify that (i.e. no testing around Metalnx).

**Comment by korydraughn** [comment]
After a lot of reading and debugging, I was able to update the jaxb2-maven-plugin version and configuration to get jargon-irods-ext compiling.

We are now ready to move things forward.

**Comment by korydraughn** [comment]
The jargon-extensions repo hasn't moved in 7 years, so I'm not going to include that as part of this effort.

**Comment by korydraughn** [comment]
Noting here that I've watched the full test suite for NFSRODS pass using the SNAPSHOT release of Jargon.
